"""Add study_sessions table and rewards fields

Revision ID: cd133ada29f5
Revises: ee8b37d45a91
Create Date: 2026-08-11 11:41:43.000829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd133ada29f5'
down_revision = 'ee8b37d45a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('completed_tasks', sa.Integer(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=True),
    sa.Column('pre_test_score', sa.Float(), nullable=True),
    sa.Column('post_test_score', sa.Float(), nullable=True),
    sa.Column('improvement', sa.Float(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('coins_earned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_sessions')
    # ### end Alembic commands ###
