"""Add inventory column to user

Revision ID: ee8b37d45a91
Revises: 20e84b4cce49
Create Date: 2026-08-10 17:15:59.212805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8b37d45a91'
down_revision = '20e84b4cce49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('inventory')

    # ### end Alembic commands ###
